### ISSUE TITLE
Bereal reverse-engineering hub

### ISSUE THREAD

**Issue by MrAn0nym** [userbradley/BeReal#16]
Just a suggestion but creating a bereal reverse-engineering hub (e.g. on discord) could make sense, especially as they seem to work on making reverse engineering consistently harder…

**Comment by userbradley** [comment]
Hi, thanks for your interest.

I am hesitant to do this as by putting it on Discord we're locking a lot of people out from the knowledge (requiring a user account etc) and personally I'm not a fan of discords business practices and the communities they attract.

I'm going to setup discussions on this repo as anyone can view them.

**Comment by userbradley** [comment]
Created: https://github.com/userbradley/BeReal/discussions

**Comment by userbradley** [comment]
Marking this as implemented and closed, any issues let me know
