### ISSUE TITLE
[ADD NEW API ENDPOINT]

### ISSUE THREAD

**Issue by max21910** [userbradley/BeReal#31]
Hi i just discovered new api Endpoint : 
POST https://ogma.bereal.team/chat.core.v1.ChatCoreService/SendMessage //send message
GET https://ogma.bereal.team/chat.core.v1.ChatCoreService/GetMessages //get message
GET https://ogma.bereal.team/chat.core.v1.ChatCoreService/GetConversationsById //get message with id members 
GET https://ogma.bereal.team/chat.core.v1.ChatCoreService/GetConversationFeed /get the feed
GET https://ogma.bereal.team/chat.core.v1.ChatCoreService/GetPendingInvites //get invitation
POST https://ogma.bereal.team/chat.core.v1.ChatCoreService/ClearConversation //clear message
POST https://ogma.bereal.team/chat.core.v1.ChatCoreService/GetSentInvites  // send invitation

Best,

Maxime

**Comment by userbradley** [comment]
Noiceeeeee, I'll get the added to the site at some point. You're also welcome to open a PR if you want to take a stave at it?

**Comment by max21910** [comment]
Sure i made a PR
