### ISSUE TITLE
Is it possible to get a user's posts?

### ISSUE THREAD

**Issue by treehousekingcomic** [userbradley/BeReal#8]
Inspecting the network requests and their responses, posts have their image URL in this form:
 `/Photos/[userId]/post/[imageId].webp`

Is it possible to guess the `imageId` somehow?

**Comment by userbradley** [comment]
Have a look at https://github.com/notmarek/BeFake

---

_closing issue as not planned_

**Comment by NeedNot** [comment]
out of curiosity did that repo crack the code on getting the ids?
